### ISSUE TITLE
Fluent query building

### ISSUE THREAD

**Issue by mikegoatly** [mikegoatly/lifti#14]
Have a think about what a fluent API for building queries would look like. This would likely be provided as an additional nuget package, e.g. Lifti.FluentQueries.

Perhaps something like:

``` csharp
index.Query().For("search text").And.For("something else").Execute();

index.Query()
    .InField("FieldName", fieldSearch => fieldSearch.For("something").Or.For("another"))
    .Or.InField("FIeld2", fieldSearch => fieldSearch.For("foo"))
    .Execute();
```

**Comment by mikegoatly** [comment]
This would allow for queries to be built up dynamically in a reasonably easy way, without having to resort to the raw IQueryPart implementations.

**Comment by noncommunicado** [comment]
+1

**Comment by mikegoatly** [comment]
I'm starting to look into this now...

**Comment by mikegoatly** [comment]
This will be in the 6.3.0 release. Docs are [here](https://mikegoatly.github.io/lifti/docs/searching/manually-constructing-queries/)
