### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by RajeshDhalange** [mikegoatly/lifti#29]
Now need to build to index every time, right?
I want to use this in the desktop application so can we not store index/snapshot after the index building as a file and pack with setup and load whenever need at run time?

**Comment by mikegoatly** [comment]
You should be able to do exactly what you want using [index serialization](https://mikegoatly.github.io/lifti/docs/serialization/) - does that help?

**Comment by RajeshDhalange** [comment]
Not understanding how to store? 
Can you please give some sample code to store the index in a file or SQLite DB or LiteDb and build again index from the same?

**Comment by mikegoatly** [comment]
LIFTI only currently supports serializing to a binary format at the moment - you could store that in a database as a blob of some sort, but in a desktop app you might as well store it as a file.

The example in the documentation shows how to serialize an index to a stream - all you'd need to do is change the sort of stream you're writing to (i.e. a FileStream) :

``` csharp
// Create a full text index with default settings
var index = new FullTextIndexBuilder<int>().Build();

// Index some sample data
await index.AddAsync(1, "This is some text associated with A: fizz");
await index.AddAsync(2, "Some buzz text for B");
await index.AddAsync(3, "Text associated with C is both fizz and buzz");

// The location of your index file is obviously up to you
var indexPath = Path.Combine(
	Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), 
	"index.dat");

// This will write the current index snapshot out to the file
var serializer = new BinarySerializer<int>();
using var stream = File.OpenWrite(indexPath)
{
	await serializer.SerializeAsync(index, stream, disposeStream: false);
}
```

To read the index state back, e.g. when the application is starting up again, you just have to deserialize the index state from the file *immediately after the index has been built*:

``` csharp
var index = new FullTextIndexBuilder<int>().Build();
var serializer = new BinarySerializer<int>();
using (var stream = File.OpenRead(indexPath))
{
	await serializer.DeserializeAsync(index, stream);
}
```

Does that help?

**Comment by RajeshDhalange** [comment]
Thanks its working

**Comment by pazicb** [comment]
Hello,
the given example works fine. But if I index the object, I get the error when searching
Lifti.LiftiException: Field id 1 has no associated field name
How should I proceed when I index an object and need to save the index to disk?

**Comment by mikegoatly** [comment]
@pazicb Have you followed the [documentation for configuring the index](https://mikegoatly.github.io/lifti/docs/index-construction/withobjecttokenization/) so that it can accept an object? If you still think you're running into a bug, please can you raise it as a separate issue.
