### ISSUE TITLE
Fuzzy Search

### ISSUE THREAD

**Issue by thebestgin** [mikegoatly/lifti#34]
Really cool search library.

The only thing I'm still missing is a fuzzy search.
Did I miss something?
Is fuzzy search planned?

**Comment by mikegoatly** [comment]
Thanks! There's nothing planned right now, but that's a good suggestion.

Is there a particular implementation of fuzzy searching your talking about? E.g. skipping missing letters, dealing with character transposition, or character substitution?

**Comment by thebestgin** [comment]
Skipping missing letters and typo compensation would be helpful in my opinion. I think "Levenshtein distance" is a good simple solution.

**Comment by Muchaszewski** [comment]
I think a big feature to this (as of right now) would be partial word matching like right now you cannot search for Charcoal by searching for coal. There is also no wildcard that would also "fix" the issue with this.  

Full fuzzy search with Levenshtein distance would be perfect, but you can also go with smaller steps of just wildcards. 

Would love to see this improved as you have very solid foundation to have a great library!

**Comment by mikegoatly** [comment]
@Muchaszewski Thanks - I've created a separate issue (#39) for this. I think that both of these features are great suggestions. I'm probably going to have a stab at #39 first because I can intuit it a bit easier and it'll ease me back into this codebase!

**Comment by mikegoatly** [comment]
I've been working on the implementation for this over the weekend. 

The core `IQueryPart` logic is covered off in the `fuzzy-match` branch. The only work left to do is to introduce the query syntax for it. I've not really got anything smart up my sleeve as far as the operator goes, so it might end up using something like ```?``` leading the search term to indicate fuzzyness.

The implementation can handle substitutions, deletions and insertions, so this:

```
?SERCH
```

Would match SEA*R*CH, *P*ERCH and SER

**Comment by mikegoatly** [comment]
The core logic for this has been merged into the v3.0.0 branch.

I want to allow to optionally make the "?" operator redundant if fuzzy searching is the default searching that required in the index. I'm currently thinking to allow this as being configuration that can be applied to a `FullTextIndexBuilder`.

**Comment by mikegoatly** [comment]
Implemented in v3 - [docs](https://mikegoatly.github.io/lifti/docs/searching/#fuzzy-matching)
