### ISSUE TITLE
Can field restrictions be used with fuzzy and wild card matching?

### ISSUE THREAD

**Issue by h0lg** [mikegoatly/lifti#53]
I notice unexpected behavior when combining **field restrictions** with either **fuzzy** or **wild card** matching.

If I have an indexed model Video with `term` in the keywords, but not in the title, the query `title=term` will not match the keywords - as expected. Also exact word queries like `title="exact term"` seem to work fine.

But both queries `title=?term` and `title=term*` **seem to ignore the title field filter** and match `term` in the keywords as well.

Neither the [doco](https://mikegoatly.github.io/lifti/docs/searching/lifti-query-syntax/#field-restrictions-field) nor the [tests](https://github.com/mikegoatly/lifti/blob/6dff0f26d6294f04ab2111e74b55fc69f751e637/test/Lifti.Tests/Querying/QueryParserTests.cs#L282) hint at this behavior - making it feel like a bug.

**Comment by mikegoatly** [comment]
Yeah, it was a bug- I noticed it the other day and it should be fixed in v3.5.1 - can you try updating to that?

**Comment by h0lg** [comment]
Yes, this is indeed fixed in 3.5.1 and works as expected. My bad, I didn't check whether I was on the latest version.

**Comment by mikegoatly** [comment]
Not a problem, glad it works. I should have raised an issue to track it, it would have been more obvious then!
