### ISSUE TITLE
Outdated NuGet dependencies

### ISSUE THREAD

**Issue by llampret** [mikegoatly/lifti#62]
Would it be possible to update NuGets ?

**Comment by mikegoatly** [comment]
Hi @llampret as far as I can tell the nuget is all up to date with the [latest release (v3.5.2)] (https://github.com/mikegoatly/lifti/releases/tag/v3.5.2) - if you're referring to the work that's ongoing for the v4.0.0 release, then that's not really ready to ship - I'm still making a couple of tweaks to the APIs.

If I've got that wrong I'll happily re-open the issue, but I'll close it for now.

**Comment by llampret** [comment]
Hey @mikegoatly,
sorry I should have specified better.

I was referring to NuGets used inside Lifti.Core project
- Microsoft.Bcl.HashCode - Version="1.1.0"
- System.Collections.Immutable - Version="1.7.1"
- System.Memory - Version="4.5.4"

I'm having a problem with "System.Memory" since I have updated "System.Collections.Immutable" from 6.0.0 to 7.0.0 and its referencing "System.Memory 4.5.5" and for some reason binding redirects don't work.

This is not an urgent thing but a nice to have and if Lifti 4.0.0 is out in a month or so its also ok.

**Comment by mikegoatly** [comment]
Ah, got it. Thanks for the clarification. Sure, not a problem - that's probably a good thing do do as part of a release that has breaking changes.

**Comment by mikegoatly** [comment]
@llampret Rather than just blanket update the dependencies, I think it will be cleaner if I multi-target the package because that way most of the dependencies go away completely:

<img width="224" alt="image" src="https://user-images.githubusercontent.com/4577868/208150423-cb5cb1bc-2215-41cf-a683-00160c0e54ba.png">

This won't work if you're using something other than .NET 6 or 7, so can I check what platform you're targeting?

**Comment by llampret** [comment]
@mikegoatly Unfortunately still on .NET 4.8 and update to 6, 7 or 8.. is not yet planned 😞

**Comment by mikegoatly** [comment]
Ok , I think you should still be OK if I bump Bcl.HashCode and System. Memory for netstandard2. I'll do a bit of testing.

**Comment by mikegoatly** [comment]
@llampret Yeah, it's all good on .NET 4.8 with v4. I created a test project and added the CI build from https://pkgs.dev.azure.com/goatly/LIFTI/_packaging/lifti-ci/nuget/v3/index.json, bumped `System.Collections.Immutable` to 7.0.0 and everything worked fine. I'll try to get everything merged and released over the next few days.

**Comment by mikegoatly** [comment]
Fixed in v4
