### ISSUE TITLE
Wild card matching in exact sequence seems broken in v4

### ISSUE THREAD

**Issue by h0lg** [mikegoatly/lifti#65]
Querying with wild cards in phrases seems to be broken in v4 compared to v3.5.2.

E.g. querying above sentence for `"* to *"` (note that the `*` are inside quotes denoting a phrase) matched **_seems to be_** and **_compared to v3.5.2_** in v3.5.2, but doesn't match anything in v4.

I'm unaware of query syntax changes in this regard between the two versions. If I'm using the syntax differently from how it was intended for matching such phrases in v4, please let me know how I'd have to change it. Thanks!

**Comment by mikegoatly** [comment]
Thanks for raising this @h0lg - I've reproduced the problem with [this fiddle](https://dotnetfiddle.net/1tkg3T)

I need to do a bit of debugging to work out exactly what's going on, but hopefully it won't take too long.

**Comment by mikegoatly** [comment]
It was a silly mistake in the [optimised positional intersection logic](https://github.com/mikegoatly/lifti/commit/7db17f365c21e7d95f668c81e4318a1fd8384d19#diff-eb28da535343cb3efd99dd719ad2887689c921933cded2e8b09e36850bb920b5) - I've added an integration test at the index level to cover this case in future.

4.0.1 is publishing to nuget now - let me know if this fixes the issue for you and we can get this issue closed off.

**Comment by mikegoatly** [comment]
~Actually, I think this may only fix a subset of the scenarios - I'll take another look when I get back to my home dev environment~

@h0lg Nope, it all looks ok to me. Let me know how you get on.

**Comment by h0lg** [comment]
That seems to have worked - I can't reproduce the issue with v4.0.1 .
Thank you for the quick fix and a happy new year!
