### ISSUE TITLE
Q: is possible to fetch the whole document by Id?

### ISSUE THREAD

**Issue by tiago-soczek** [mikegoatly/lifti#86]
Hello!

Is it possible to obtain the complete document by ID? When getting the results, I would like to have all the fields and values in the document, not just the ones that matched (`FieldMatches`).

**Comment by mikegoatly** [comment]
Hi @tiago-soczek! 

There's nothing built in - there's a general expectation that you'll still be able to query the original source text/object that was used to construct the index. 

For example, when you're [extracting matched phrases](https://mikegoatly.github.io/lifti/docs/searching/search-results/extracting-matched-phrases/) from search results, you're required to pass a delegate that returns the original:

```csharp
foreach (var result in await results.CreateMatchPhrasesAsync(i => books.First(x => x.BookId == i)))
{
    Console.WriteLine($"{result.SearchResult.Key} ({result.SearchResult.Score})");

    foreach (var fieldPhrase in result.FieldPhrases)
    {
        Console.Write($"  {fieldPhrase.FoundIn}: ");
        Console.WriteLine(string.Join(", ", fieldPhrase.Phrases.Select(x => $"\"{x}\"")));
    }
}
```

One of the objectives of indexing like this is to reduce the overall memory requirements of searching across all the items - storing the the original in memory would defeat that.

**Comment by tiago-soczek** [comment]
Thanks @mikegoatly, got it! I'll change my implementation here!
