### ISSUE TITLE
Operaterrors as a text

### ISSUE THREAD

**Issue by iduducohen** [mikegoatly/lifti#90]
Is it possible to use operators or brackets as text?
For ex : search for test & 
or test (

**Comment by mikegoatly** [comment]
Hi @iduducohen, At the moment the only way to do this is to manually construct the query yourself:

```csharp
// First normalize the search text
var normalizedSearchText = index.DefaultTokenizer.Normalize("test (");

// Construct a query with a single query part
var query = new Query(new ExactWordQueryPart(normalizedSearchText));

// Execute the query
var results = index.Search(query);
```

I'm tracking issue #85 that will allow you to escape these characters.

**Comment by iduducohen** [comment]
Thank you very much for the quick reply, I will look into the matter.
In addition, is it possible to perform NOT operations?

‫בתאריך יום ב׳, 18 בדצמ׳ 2023 ב-7:54 מאת ‪Mike Goatly‬‏ <‪
***@***.***‬‏>:‬

**Comment by mikegoatly** [comment]
No, not at the moment - that's a good feature request though. I'll create an issue to track that 😊.
